language: java
jdk:
   - oraclejdk9
addons:
   sonarcloud:
      organization: "maxwellray-github"
      token:
         secure: 577804a3acb4cba0fa0e5a2df1bd0eb6a114df8d
script:
   mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
