language: java
jdk:
   - oraclejdk9
addons:
   sonarcloud:
      organization: "maxwellray-github"
      token:
         secure: 66d39d5daa7049bf89edbbddaccc63564f58ab81
script:
   mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
