language: java
jdk:
   - oraclejdk9
addons:
   sonarcloud:
      organization: "maxwellray-github"
      token:
         secure: 66d39d5daa7049bf89edbbddaccc63564f58ab81
script:
  mvn sonar:sonar \
    -Dsonar.organization=maxwellray-github \
    -Dsonar.host.url=https://sonarcloud.io \
    -Dsonar.login=66d39d5daa7049bf89edbbddaccc63564f58ab81
